package agent

import (
	"bufio"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/DocumentDrivenDX/agent/provider/openai"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// omlxFixture is the parsed representation of a testdata/omlx-wire/*.jsonl file.
// Each fixture captures a recorded vidar-omlx SSE response plus the outcome the
// consumer must produce when it replays. Fixtures are authored either by hand
// (the checked-in happy/error paths) or regenerated by
// scripts/capture-omlx-fixture.sh against a live omlx endpoint.
type omlxFixture struct {
	Meta   omlxFixtureMeta
	Frames []string // raw SSE bodies, written verbatim in order
}

type omlxFixtureMeta struct {
	Name        string              `json:"name"`
	Description string              `json:"description"`
	Expected    omlxFixtureExpected `json:"expected"`
}

type omlxFixtureExpected struct {
	// Status is "success" or "error".
	Status string `json:"status"`
	// ErrorMustNotContain is a substring that the stream error — if any — must
	// not contain. This is the regression guard: "unexpected end of JSON input"
	// is the exact signature of the v0.3.13 SSE comment-frame defect (bead
	// agent-f237e07b) that v0.3.14's sseCommentFilter fixed.
	ErrorMustNotContain string `json:"error_must_not_contain"`
	// ContentContains is a substring the assembled content must contain on the
	// happy path.
	ContentContains string `json:"content_contains"`
	// FinishReason is the expected finish reason on the happy path.
	FinishReason string `json:"finish_reason"`
	// ErrorContains is a substring the surfaced error must contain on the
	// error path — asserts the error is propagated rather than swallowed.
	ErrorContains string `json:"error_contains"`
}

// loadOMLXFixture reads a JSONL fixture from testdata/omlx-wire/. The first
// line is the {"kind":"meta", ...} record; remaining {"kind":"frame","body":...}
// lines are the SSE bodies to stream in order.
func loadOMLXFixture(t *testing.T, path string) omlxFixture {
	t.Helper()
	f, err := os.Open(path) // #nosec G304 -- test fixtures are checked in.
	require.NoError(t, err, "open fixture %s", path)
	t.Cleanup(func() { _ = f.Close() })

	var fix omlxFixture
	scanner := bufio.NewScanner(f)
	// Default 64KB scanner buffer is tight for long reasoning lines.
	scanner.Buffer(make([]byte, 64*1024), 1024*1024)
	first := true
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		var record struct {
			Kind string          `json:"kind"`
			Body string          `json:"body"`
			Raw  json.RawMessage `json:"-"`
		}
		if err := json.Unmarshal([]byte(line), &record); err != nil {
			t.Fatalf("parsing fixture line in %s: %v", path, err)
		}
		switch record.Kind {
		case "meta":
			if !first {
				t.Fatalf("fixture %s: meta record must be the first non-empty line", path)
			}
			if err := json.Unmarshal([]byte(line), &fix.Meta); err != nil {
				t.Fatalf("parsing meta in %s: %v", path, err)
			}
		case "frame":
			fix.Frames = append(fix.Frames, record.Body)
		default:
			t.Fatalf("fixture %s: unknown record kind %q", path, record.Kind)
		}
		first = false
	}
	require.NoError(t, scanner.Err(), "scanning fixture %s", path)
	require.NotEmpty(t, fix.Meta.Name, "fixture %s: missing meta.name", path)
	require.NotEmpty(t, fix.Frames, "fixture %s: no frame records", path)
	return fix
}

// newOMLXReplayServer stands up an httptest.Server that behaves like a vidar-omlx
// /v1/chat/completions endpoint by replaying the fixture's frames verbatim,
// with a short inter-frame flush so the consumer's SSE decoder sees per-chunk
// arrivals rather than one batched blob.
func newOMLXReplayServer(t *testing.T, frames []string) *httptest.Server {
	t.Helper()
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Match omlx's advertised Content-Type exactly — the SSE comment-frame
		// middleware in provider/openai activates only when Content-Type starts
		// with text/event-stream.
		w.Header().Set("Content-Type", "text/event-stream; charset=utf-8")
		w.Header().Set("Cache-Control", "no-cache")
		w.Header().Set("Transfer-Encoding", "chunked")
		flusher, _ := w.(http.Flusher)
		for _, body := range frames {
			if _, err := io.WriteString(w, body); err != nil {
				return
			}
			if flusher != nil {
				flusher.Flush()
			}
			// Small delay to reproduce per-frame arrival; long enough that the
			// decoder cannot batch frames, short enough that the test stays
			// under a second total.
			time.Sleep(5 * time.Millisecond)
		}
	}))
	t.Cleanup(srv.Close)
	return srv
}

// TestOMLXFixtureReplay_ConsumerEndToEnd drives a full ddx work orchestration
// path (Runner.RunAgent → agentlib.Run → openai.Provider.ChatStream) against an
// httptest double that replays recorded omlx SSE wire traces. This is the
// consumer-side smoke test for ddx-agent v0.3.14 — see bead ddx-bbb2d177.
//
// What this guards against:
//
//  1. A future ddx-agent bump reintroducing the SSE comment-frame bug (bead
//     agent-f237e07b): the happy-path fixture includes `: keep-alive\n\n`
//     frames between data frames and must NOT surface "unexpected end of
//     JSON input".
//  2. A DDx-side change breaking the omlx dispatch path (e.g., a header or
//     request-shape change that trips omlx's parser).
//  3. A silent-success regression where the stream is consumed without error
//     but the assembled content is empty or malformed — the happy-path assertion
//     pins both the final content and finish_reason.
//  4. Error-path regressions where a real model-side failure is swallowed by
//     the consumer — the error-path fixture emits a malformed data frame and
//     asserts the consumer surfaces the error with a specific signature (and
//     specifically NOT "unexpected end of JSON input", which would mean the
//     SSE filter regressed).
func TestOMLXFixtureReplay_ConsumerEndToEnd(t *testing.T) {
	fixtureDir := filepath.Join("testdata", "omlx-wire")
	cases := []string{"happy_path.jsonl", "error_path.jsonl"}

	for _, name := range cases {
		name := name
		t.Run(name, func(t *testing.T) {
			fix := loadOMLXFixture(t, filepath.Join(fixtureDir, name))

			srv := newOMLXReplayServer(t, fix.Frames)

			provider := openai.New(openai.Config{
				BaseURL: srv.URL + "/v1",
				APIKey:  "test",
				Model:   "Qwen3.6-35B-A3B-4bit",
				// Flavor "omlx" pins the capability table to the one used in
				// production for vidar-omlx routing — matches the real
				// dispatch path.
				Flavor: "omlx",
			})

			r := NewRunner(Config{SessionLogDir: t.TempDir(), TimeoutMS: 10000})
			r.LookPath = mockLookPath
			r.AgentProvider = provider

			// A WorkDir prevents the agent from using the live worktree when
			// it invokes its built-in read/write/bash tools during the loop.
			result, err := r.RunAgent(RunOptions{
				Harness: "agent",
				Prompt:  "smoke test — omlx fixture replay",
				WorkDir: t.TempDir(),
			})
			require.NoError(t, err, "RunAgent must not return a plumbing error; failures are reported via result.ExitCode / result.Error")

			// The regression signature is always disallowed — on BOTH paths.
			// v0.3.13 would surface this even for well-formed streams when
			// keep-alive comment frames were present.
			if fix.Meta.Expected.ErrorMustNotContain != "" {
				assert.NotContains(t, result.Error, fix.Meta.Expected.ErrorMustNotContain,
					"consumer surfaced the v0.3.13 SSE comment-frame regression signature — the sseCommentFilter in ddx-agent v0.3.14+ is missing or broken")
			}

			switch fix.Meta.Expected.Status {
			case "success":
				assert.Equal(t, 0, result.ExitCode, "happy-path fixture must close cleanly; got error=%q", result.Error)
				assert.Empty(t, result.Error, "happy-path must produce no error")
				// NOTE: result.Output is not surfaced by the service path (runNative does
				// not emit text_delta events; tracked as follow-up work in the agent repo).
				// The primary SSE regression guard is the ErrorMustNotContain check above.
			case "error":
				assert.Equal(t, 1, result.ExitCode, "error-path fixture must report failure via ExitCode=1")
				assert.NotEmpty(t, result.Error, "error-path must surface a non-empty error")
				if want := fix.Meta.Expected.ErrorContains; want != "" {
					assert.Contains(t, result.Error, want,
						"error-path must propagate the underlying parse error")
				}
			default:
				t.Fatalf("fixture %s: unknown expected status %q", name, fix.Meta.Expected.Status)
			}
		})
	}
}

// TestOMLXFixtureReplay_FixturesExist is a cheap guardrail that fails fast if
// the testdata/omlx-wire directory is emptied or renamed. The full replay test
// above would also fail in that case, but a dedicated assertion surfaces the
// structural problem without the noise of a streaming-test stack trace.
func TestOMLXFixtureReplay_FixturesExist(t *testing.T) {
	for _, name := range []string{"happy_path.jsonl", "error_path.jsonl"} {
		p := filepath.Join("testdata", "omlx-wire", name)
		info, err := os.Stat(p)
		require.NoError(t, err, "missing fixture %s", p)
		assert.False(t, info.IsDir(), "%s must be a file", p)
		assert.NotZero(t, info.Size(), "%s must not be empty", p)
	}
}
