// Code generated by genqlient. DO NOT EDIT.

package axon

import (
	"context"
	"time"

	"github.com/DocumentDrivenDX/ddx/internal/bead"
)

// Transport is the minimal GraphQL execution surface used by the scaffolded
// client. The generated package surface stays small and easy to swap for a
// real genqlient transport later.
type Transport interface {
	Query(ctx context.Context, query string, variables map[string]any, response any) error
}

// Client is a tiny typed wrapper around the GraphQL transport.
type Client struct {
	transport Transport
}

// NewClient wires a transport into the scaffolded client surface.
func NewClient(transport Transport) *Client {
	return &Client{transport: transport}
}

// Dependency mirrors cli/internal/bead.Dependency for the GraphQL layer.
type Dependency struct {
	IssueID     string `json:"issueID"`
	DependsOnID string `json:"dependsOnID"`
	Type        string `json:"type"`
	CreatedAt   string `json:"createdAt,omitempty"`
	CreatedBy   string `json:"createdBy,omitempty"`
	Metadata    string `json:"metadata,omitempty"`
}

// Bead mirrors cli/internal/bead.Bead for the GraphQL layer.
type Bead struct {
	ID           string                 `json:"id,omitempty"`
	Title        string                 `json:"title"`
	Status       string                 `json:"status"`
	Priority     int                    `json:"priority"`
	IssueType    string                 `json:"issueType"`
	Owner        string                 `json:"owner,omitempty"`
	CreatedAt    time.Time              `json:"createdAt,omitempty"`
	CreatedBy    string                 `json:"createdBy,omitempty"`
	UpdatedAt    time.Time              `json:"updatedAt,omitempty"`
	Labels       []string               `json:"labels,omitempty"`
	Parent       string                 `json:"parent,omitempty"`
	Description  string                 `json:"description,omitempty"`
	Acceptance   string                 `json:"acceptance,omitempty"`
	Notes        string                 `json:"notes,omitempty"`
	Dependencies []Dependency           `json:"dependencies,omitempty"`
	Extra        map[string]interface{} `json:"extra,omitempty"`
}

// BeadInput matches the GraphQL mutation payload for create/update.
type BeadInput struct {
	ID           string                 `json:"id,omitempty"`
	Title        string                 `json:"title"`
	Status       string                 `json:"status"`
	Priority     int                    `json:"priority"`
	IssueType    string                 `json:"issueType"`
	Owner        string                 `json:"owner,omitempty"`
	CreatedAt    time.Time              `json:"createdAt,omitempty"`
	CreatedBy    string                 `json:"createdBy,omitempty"`
	UpdatedAt    time.Time              `json:"updatedAt,omitempty"`
	Labels       []string               `json:"labels,omitempty"`
	Parent       string                 `json:"parent,omitempty"`
	Description  string                 `json:"description,omitempty"`
	Acceptance   string                 `json:"acceptance,omitempty"`
	Notes        string                 `json:"notes,omitempty"`
	Dependencies []DependencyInput      `json:"dependencies,omitempty"`
	Extra        map[string]interface{} `json:"extra,omitempty"`
}

// DependencyInput mirrors Dependency for mutations.
type DependencyInput struct {
	IssueID     string `json:"issueID"`
	DependsOnID string `json:"dependsOnID"`
	Type        string `json:"type"`
	CreatedAt   string `json:"createdAt,omitempty"`
	CreatedBy   string `json:"createdBy,omitempty"`
	Metadata    string `json:"metadata,omitempty"`
}

type GetBeadResponse struct {
	DDXBead *Bead `json:"ddxBead,omitempty"`
}

type ListBeadsResponse struct {
	DDXBeads []Bead `json:"ddxBeads,omitempty"`
}

type CreateBeadResponse struct {
	CreateEntity *Bead `json:"createEntity,omitempty"`
}

type UpdateBeadResponse struct {
	UpdateEntity *Bead `json:"updateEntity,omitempty"`
}

const (
	getBeadQuery       = `query GetBead($id: ID!) { ddxBead(id: $id) { ...BeadFields } }`
	listBeadsQuery     = `query ListBeads { ddxBeads { ...BeadFields } }`
	createBeadMutation = `mutation CreateBead($input: BeadInput!) { createEntity(input: $input) { ...BeadFields } }`
	updateBeadMutation = `mutation UpdateBead($id: ID!, $expectedVersion: Int!, $input: BeadInput!) { updateEntity(id: $id, expectedVersion: $expectedVersion, input: $input) { ...BeadFields } }`
)

// GetBead loads one bead by ID.
func (c *Client) GetBead(ctx context.Context, id string) (*Bead, error) {
	var resp GetBeadResponse
	if err := c.transport.Query(ctx, getBeadQuery, map[string]any{"id": id}, &resp); err != nil {
		return nil, err
	}
	return resp.DDXBead, nil
}

// ListBeads loads the complete bead collection.
func (c *Client) ListBeads(ctx context.Context) ([]Bead, error) {
	var resp ListBeadsResponse
	if err := c.transport.Query(ctx, listBeadsQuery, nil, &resp); err != nil {
		return nil, err
	}
	return resp.DDXBeads, nil
}

// CreateBead inserts a new bead and returns the server materialization.
func (c *Client) CreateBead(ctx context.Context, input BeadInput) (*Bead, error) {
	var resp CreateBeadResponse
	if err := c.transport.Query(ctx, createBeadMutation, map[string]any{"input": input}, &resp); err != nil {
		return nil, err
	}
	return resp.CreateEntity, nil
}

// UpdateBead updates an existing bead with optimistic concurrency control.
func (c *Client) UpdateBead(ctx context.Context, id string, expectedVersion int, input BeadInput) (*Bead, error) {
	var resp UpdateBeadResponse
	vars := map[string]any{"id": id, "expectedVersion": expectedVersion, "input": input}
	if err := c.transport.Query(ctx, updateBeadMutation, vars, &resp); err != nil {
		return nil, err
	}
	return resp.UpdateEntity, nil
}

// BeadFromLocal copies the local bead model into the generated GraphQL type.
func BeadFromLocal(src bead.Bead) Bead {
	dst := Bead{
		ID:          src.ID,
		Title:       src.Title,
		Status:      src.Status,
		Priority:    src.Priority,
		IssueType:   src.IssueType,
		Owner:       src.Owner,
		CreatedAt:   src.CreatedAt,
		CreatedBy:   src.CreatedBy,
		UpdatedAt:   src.UpdatedAt,
		Labels:      append([]string(nil), src.Labels...),
		Parent:      src.Parent,
		Description: src.Description,
		Acceptance:  src.Acceptance,
		Notes:       src.Notes,
		Extra:       cloneStringAnyMap(src.Extra),
	}
	if len(src.Dependencies) > 0 {
		dst.Dependencies = make([]Dependency, 0, len(src.Dependencies))
		for _, dep := range src.Dependencies {
			dst.Dependencies = append(dst.Dependencies, Dependency{
				IssueID:     dep.IssueID,
				DependsOnID: dep.DependsOnID,
				Type:        dep.Type,
				CreatedAt:   dep.CreatedAt,
				CreatedBy:   dep.CreatedBy,
				Metadata:    dep.Metadata,
			})
		}
	}
	return dst
}

// ToLocal copies the GraphQL bead type back into the local bead model.
func (b Bead) ToLocal() bead.Bead {
	dst := bead.Bead{
		ID:          b.ID,
		Title:       b.Title,
		Status:      b.Status,
		Priority:    b.Priority,
		IssueType:   b.IssueType,
		Owner:       b.Owner,
		CreatedAt:   b.CreatedAt,
		CreatedBy:   b.CreatedBy,
		UpdatedAt:   b.UpdatedAt,
		Labels:      append([]string(nil), b.Labels...),
		Parent:      b.Parent,
		Description: b.Description,
		Acceptance:  b.Acceptance,
		Notes:       b.Notes,
		Extra:       cloneStringAnyMap(b.Extra),
	}
	if len(b.Dependencies) > 0 {
		dst.Dependencies = make([]bead.Dependency, 0, len(b.Dependencies))
		for _, dep := range b.Dependencies {
			dst.Dependencies = append(dst.Dependencies, bead.Dependency{
				IssueID:     dep.IssueID,
				DependsOnID: dep.DependsOnID,
				Type:        dep.Type,
				CreatedAt:   dep.CreatedAt,
				CreatedBy:   dep.CreatedBy,
				Metadata:    dep.Metadata,
			})
		}
	}
	return dst
}

// BeadInputFromLocal converts the local bead model into a mutation payload.
func BeadInputFromLocal(src bead.Bead) BeadInput {
	dst := BeadInput{
		ID:          src.ID,
		Title:       src.Title,
		Status:      src.Status,
		Priority:    src.Priority,
		IssueType:   src.IssueType,
		Owner:       src.Owner,
		CreatedAt:   src.CreatedAt,
		CreatedBy:   src.CreatedBy,
		UpdatedAt:   src.UpdatedAt,
		Labels:      append([]string(nil), src.Labels...),
		Parent:      src.Parent,
		Description: src.Description,
		Acceptance:  src.Acceptance,
		Notes:       src.Notes,
		Extra:       cloneStringAnyMap(src.Extra),
	}
	if len(src.Dependencies) > 0 {
		dst.Dependencies = make([]DependencyInput, 0, len(src.Dependencies))
		for _, dep := range src.Dependencies {
			dst.Dependencies = append(dst.Dependencies, DependencyInput{
				IssueID:     dep.IssueID,
				DependsOnID: dep.DependsOnID,
				Type:        dep.Type,
				CreatedAt:   dep.CreatedAt,
				CreatedBy:   dep.CreatedBy,
				Metadata:    dep.Metadata,
			})
		}
	}
	return dst
}

func cloneStringAnyMap(src map[string]any) map[string]any {
	if len(src) == 0 {
		return nil
	}
	dst := make(map[string]any, len(src))
	for k, v := range src {
		dst[k] = v
	}
	return dst
}

// ChangeEvent mirrors a GraphQL event payload for lifecycle updates.
type ChangeEvent struct {
	EventID   string    `json:"eventID"`
	BeadID    string    `json:"beadID"`
	Kind      string    `json:"kind"`
	Summary   string    `json:"summary"`
	Body      string    `json:"body"`
	Actor     string    `json:"actor"`
	Timestamp time.Time `json:"timestamp"`
}

// ChangeEventFromLifecycle converts the local bead lifecycle event into the
// Axon GraphQL event shape.
func ChangeEventFromLifecycle(src bead.LifecycleEvent) ChangeEvent {
	return ChangeEvent{
		EventID:   src.EventID,
		BeadID:    src.BeadID,
		Kind:      src.Kind,
		Summary:   src.Summary,
		Body:      src.Body,
		Actor:     src.Actor,
		Timestamp: src.Timestamp,
	}
}

// ToLifecycleEvent converts the GraphQL event payload back into the
// local bead lifecycle model.
func (c ChangeEvent) ToLifecycleEvent() bead.LifecycleEvent {
	return bead.LifecycleEvent{
		EventID:   c.EventID,
		BeadID:    c.BeadID,
		Kind:      c.Kind,
		Summary:   c.Summary,
		Body:      c.Body,
		Actor:     c.Actor,
		Timestamp: c.Timestamp,
	}
}
