import { NodeInfoStore } from "../plugins/houdini-svelte/stores/NodeInfo";
import { TestTypenameStore } from "../plugins/houdini-svelte/stores/TestTypename";
import type { Cache as InternalCache } from "./cache/cache";
import type { CacheTypeDef } from "./generated";
import { Cache } from "./public";
export * from "./client";
export * from "./lib";
export function graphql(str: "query NodeInfo {\n\tnodeInfo {\n\t\tid\n\t\tname\n\t}\n}\n"): NodeInfoStore;
export function graphql(str: "query TestTypename {\n\t__typename\n}\n"): TestTypenameStore;
export declare function graphql<_Payload, _Result = _Payload>(str: TemplateStringsArray): _Result;
export declare const cache: Cache<CacheTypeDef>;
export declare function getCache(): InternalCache;